"""Public facade for semantic workbench chrome components.

Native PySide6 types stay in place. Style is applied with validated dynamic
properties and ThemeService tokens. This module is not a second theme owner.
"""

from .apply import (
    annotate_section,
    apply_elided_text,
    apply_text_style,
    apply_ui_style,
    combo_is_protected,
    component_spec,
    refresh_ui_style,
)
from .factories import (
    annotate_form_fields,
    annotate_inspector_control,
    annotate_sections,
    create_alert,
    create_badge,
    create_button,
    create_card,
    create_check_box,
    create_combo_box,
    create_double_spin_box,
    create_empty_state,
    create_icon_button,
    create_line_edit,
    create_plain_text_edit,
    create_radio_button,
    create_spin_box,
    create_tabs,
    style_accept_cancel,
    style_button,
    style_dialog_button_box,
)
from .feedback import (
    ask_confirmation,
    present_error,
    present_warning,
    set_busy_state,
    set_validation_state,
    style_message_box,
    style_progress_bar,
)
from .inspection import inspect_chrome, is_inspection_exempt
from .layout_signature import capture_layout_signature, signature_paths
from .models import (
    PROPERTY_BUSY,
    PROPERTY_INVALID,
    PROPERTY_ROLE,
    PROPERTY_SIZE,
    PROPERTY_TEXT_ROLE,
    PROPERTY_TONE,
    PROPERTY_VARIANT,
    UiComponentSpec,
    UiRole,
    UiSize,
    UiTextRole,
    UiTone,
    UiVariant,
)

__all__ = [
    "PROPERTY_BUSY",
    "PROPERTY_INVALID",
    "PROPERTY_ROLE",
    "PROPERTY_SIZE",
    "PROPERTY_TEXT_ROLE",
    "PROPERTY_TONE",
    "PROPERTY_VARIANT",
    "UiComponentSpec",
    "UiRole",
    "UiSize",
    "UiTextRole",
    "UiTone",
    "UiVariant",
    "annotate_form_fields",
    "ask_confirmation",
    "annotate_inspector_control",
    "annotate_section",
    "annotate_sections",
    "apply_elided_text",
    "apply_text_style",
    "apply_ui_style",
    "capture_layout_signature",
    "combo_is_protected",
    "component_spec",
    "create_alert",
    "create_badge",
    "create_button",
    "create_card",
    "create_check_box",
    "create_combo_box",
    "create_double_spin_box",
    "create_empty_state",
    "create_icon_button",
    "create_line_edit",
    "create_plain_text_edit",
    "create_radio_button",
    "create_spin_box",
    "create_tabs",
    "inspect_chrome",
    "is_inspection_exempt",
    "present_error",
    "present_warning",
    "refresh_ui_style",
    "set_busy_state",
    "set_validation_state",
    "signature_paths",
    "style_accept_cancel",
    "style_button",
    "style_dialog_button_box",
    "style_message_box",
    "style_progress_bar",
]
