"""Concrete controllers for the first-party Matplotlib component set."""

from __future__ import annotations

from ._helpers import (
    _positive,
    _nonnegative,
    _optional_text,
    _primary_font_family,
    _url_sequence,
    _line_pattern,
    _marker_spec,
    _connectors,
    _optional_sketch,
    _set_sketch,
    _ARTIST_EXPORT_PROPERTIES,
    _normalize_color,
    _read_color,
    _pair,
    _nondegenerate_pair,
    _positive_pair,
    _anchor,
    _legend_anchor,
    _DEFAULT_FONT_SPEC,
    _rectangle,
    _in_axes_rectangle,
    _in_axes_range,
    _optional_extent,
    IN_AXES_IMAGE_MIMES,
    _validate_in_axes_image_data,
    decode_in_axes_image,
    _optional_pair,
    _aspect,
    _spine_position,
    _set_spine_bounds,
    LINESTYLE_ALIASES,
    normalize_linestyle,
    normalize_reference_positions,
    normalize_position_ref,
    FIXED_REFLECTION_PLACEMENT,
    REFERENCE_MARKS_DATA_KEYS,
    _required_position_ref,
    normalize_reflection_placement,
    complete_reference_marks_data,
    normalize_reference_marks_data,
    reflection_placement_is_automatic,
    _y_lower_reserve_value,
    _figure_style,
    _rotation,
    _legend_location,
    _column_reference,
    _finite_number,
    _exact_data_fields,
    _marker,
    _axis_name,
    _level,
)

from .containers import (
    ContainerController,
    FigureController,
    AxesController,
)

from .axes_semantics import (
    AxisComponentController,
    AxisController,
    XAxisController,
    YAxisController,
    SpineController,
    TickGroupController,
    TickLabelGroupController,
    GridController,
)

from .text import (
    TextController,
    TitleController,
    AxisLabelController,
)

from .annotation import (
    ANNOTATION_ARROW_STYLES,
    ANNOTATION_CONNECTION_STYLES,
    AnnotationController,
    COORDINATE_SYSTEMS,
    TARGET_COORDINATE_SYSTEMS,
    TEXT_COORDINATE_SYSTEMS,
    coordinate_system_name,
)

from .legend import (
    LegendController,
)

from .in_axes import (
    _IN_AXES_COMMON_PROPERTIES,
    InAxesController,
    ZoomInAxesController,
    ImageInAxesController,
)

from .lines import (
    LineController,
    FunctionCurveController,
    DataPlotController,
    FitCurveController,
    InterpolationController,
)

from .collections import (
    CollectionController,
    ReferenceMarksController,
    _ReferenceGuideController,
    ReferenceLineController,
    ReferenceBandController,
    ScatterController,
)

from .field_2d import (
    ContourController,
    Field2DController,
    HeatmapController,
    PseudocolorController,
)

from .errorbar import (
    ERROR_BAR_DATA_FIELDS,
    ERROR_BAR_V20_PROPERTY_KEYS,
    ERROR_BAR_V21_DEFAULTS,
    ERROR_BAR_STRUCTURE_PROPERTY_KEYS,
    ErrorBarController,
)

from .colorbar import (
    ColorbarController,
    ColorbarRuntimeConfiguration,
)
from .secondary_axis import (
    SecondaryAxisController,
    SecondaryAxisRemovalHandle,
    SecondaryAxisRuntime,
)

from .registry_bridge import (
    CONTROLLER_TYPES,
    validate_controller_contracts,
    controller_type_for,
    create_controller,
)
from ..matplotlib_removal import InAxesRemovalHandle


__all__ = [
    "_positive",
    "_nonnegative",
    "_optional_text",
    "_primary_font_family",
    "_url_sequence",
    "_line_pattern",
    "_marker_spec",
    "_connectors",
    "_optional_sketch",
    "_set_sketch",
    "_ARTIST_EXPORT_PROPERTIES",
    "_normalize_color",
    "_read_color",
    "_pair",
    "_nondegenerate_pair",
    "_positive_pair",
    "_anchor",
    "_legend_anchor",
    "_DEFAULT_FONT_SPEC",
    "_rectangle",
    "_in_axes_rectangle",
    "_in_axes_range",
    "_optional_extent",
    "IN_AXES_IMAGE_MIMES",
    "_validate_in_axes_image_data",
    "decode_in_axes_image",
    "_optional_pair",
    "_aspect",
    "_spine_position",
    "_set_spine_bounds",
    "LINESTYLE_ALIASES",
    "normalize_linestyle",
    "normalize_reference_positions",
    "normalize_position_ref",
    "FIXED_REFLECTION_PLACEMENT",
    "REFERENCE_MARKS_DATA_KEYS",
    "_required_position_ref",
    "normalize_reflection_placement",
    "complete_reference_marks_data",
    "normalize_reference_marks_data",
    "reflection_placement_is_automatic",
    "_y_lower_reserve_value",
    "_figure_style",
    "_rotation",
    "_legend_location",
    "_column_reference",
    "_finite_number",
    "_exact_data_fields",
    "_marker",
    "_axis_name",
    "_level",
    "ContainerController",
    "FigureController",
    "AxesController",
    "AxisComponentController",
    "AxisController",
    "XAxisController",
    "YAxisController",
    "SpineController",
    "TickGroupController",
    "TickLabelGroupController",
    "GridController",
    "TextController",
    "TitleController",
    "AxisLabelController",
    "ANNOTATION_ARROW_STYLES",
    "ANNOTATION_CONNECTION_STYLES",
    "AnnotationController",
    "COORDINATE_SYSTEMS",
    "TARGET_COORDINATE_SYSTEMS",
    "TEXT_COORDINATE_SYSTEMS",
    "coordinate_system_name",
    "LegendController",
    "_IN_AXES_COMMON_PROPERTIES",
    "InAxesController",
    "ZoomInAxesController",
    "ImageInAxesController",
    "LineController",
    "FunctionCurveController",
    "DataPlotController",
    "FitCurveController",
    "InterpolationController",
    "CollectionController",
    "ReferenceMarksController",
    "_ReferenceGuideController",
    "ReferenceLineController",
    "ReferenceBandController",
    "ScatterController",
    "ERROR_BAR_DATA_FIELDS",
    "ERROR_BAR_STRUCTURE_PROPERTY_KEYS",
    "ERROR_BAR_V20_PROPERTY_KEYS",
    "ERROR_BAR_V21_DEFAULTS",
    "ErrorBarController",
    "Field2DController",
    "PseudocolorController",
    "HeatmapController",
    "ContourController",
    "ColorbarController",
    "ColorbarRuntimeConfiguration",
    "SecondaryAxisController",
    "SecondaryAxisRemovalHandle",
    "SecondaryAxisRuntime",
    "CONTROLLER_TYPES",
    "validate_controller_contracts",
    "controller_type_for",
    "create_controller",
    "InAxesRemovalHandle",
]
