"""Application chrome theme. Not Matplotlib Figure style.

``ThemeService`` publishes font, QPalette, QSS tokens, density, and icon roles.
``bind_qss`` retokenizes widgets. Palette, metrics, and icons are the
injectable transaction step-4 appliers.
"""

from mygui.application_settings.runtime import APPEARANCE_LIVE_KEYS

from .binder import (
    ThemeSettingsBinder,
    apply_committed_appearance,
    compose_theme_runtime_applier,
    preferences_from_appearance,
    preferences_from_snapshot,
)
from .errors import (
    ThemeApplyError,
    ThemeError,
    ThemeRollbackError,
    ThemeValidationError,
)
from .icons import CachingThemeIconProvider, IconCacheKey, IconRole
from .metrics import DENSITY_BANDS, DensityBand, build_density_metrics
from .models import (
    APPLY_STEPS,
    AppearancePreferences,
    Density,
    DensityMetrics,
    EffectiveScheme,
    ThemeHealth,
    ThemeMode,
    ThemeSnapshot,
)
from .participants import SIZE_PARTICIPANTS, ThemeMetricsApplier
from .ports import (
    MetricsBindingPort,
    NullThemeIconProvider,
    PlaceholderQssRenderer,
    QssDocumentRenderer,
    RecordingThemeBindingPort,
    ThemeBindingPort,
    ThemeBindingRegistry,
    ThemeIconProvider,
)
from .qss import (
    APPLICATION_QSS_RESOURCE,
    BundledQssRenderer,
    COMPONENT_QSS_RESOURCE,
    DIALOG_QSS_RESOURCE,
    MAINWINDOW_QSS_RESOURCE,
    QssResourceBundle,
    QssThemeBinding,
    bind_qss,
    bind_qss_text,
    bind_widget_qss,
    binding_count,
    compose_component_stylesheet,
    current_qss_tokens,
    current_theme_binding,
    default_qss_binding,
    install_theme_binding,
    isolate_matplotlib_canvas,
    qss_bind_key,
    rebind_qss_bindings,
    render_application_stylesheet,
    render_resource_stylesheet,
    reset_qss_bindings_for_tests,
    watch_qss_tokens,
)
from .runtime import (
    apply_theme_chrome,
    compose_theme_service,
    compose_theme_snapshot,
    current_density_metrics,
    current_theme_snapshot,
    default_theme_runtime,
)
from .service import ThemeFaultHooks, ThemeService
from .system import FakeStyleHints, resolve_effective_scheme, scheme_from_palette
from .tokens import (
    CONTRAST_BOUNDARY_PAIRS,
    CONTRAST_PAIRS_BODY,
    CONTRAST_PAIRS_FOCUS,
    CONTRAST_TEXT_PAIRS,
    DARK_CORE_TOKENS,
    DARK_QSS_TOKENS,
    DARK_ROLE_COLORS,
    FONT_FAMILIES,
    FONT_SIZE_PT,
    ICON_QSS_TOKEN_NAMES,
    ICON_ROLES,
    LIGHT_COLOR_TOKENS,
    LIGHT_CONTROL_SIZES,
    LIGHT_QSS_TOKENS,
    LIGHT_RADII,
    LIGHT_ROLE_COLORS,
    LIGHT_SPACING,
    QSS_TOKEN_NAMES,
    contrast_ratio,
    qss_tokens_for_scheme,
)
from .windows import subscribe_theme_window, theme_construction_batch

QssThemeBindingPort = ThemeBindingPort

__all__ = [
    "APPEARANCE_LIVE_KEYS",
    "APPLICATION_QSS_RESOURCE",
    "APPLY_STEPS",
    "BundledQssRenderer",
    "COMPONENT_QSS_RESOURCE",
    "AppearancePreferences",
    "CONTRAST_BOUNDARY_PAIRS",
    "CONTRAST_PAIRS_BODY",
    "CONTRAST_PAIRS_FOCUS",
    "CONTRAST_TEXT_PAIRS",
    "CachingThemeIconProvider",
    "DARK_CORE_TOKENS",
    "DARK_QSS_TOKENS",
    "DARK_ROLE_COLORS",
    "DIALOG_QSS_RESOURCE",
    "DENSITY_BANDS",
    "Density",
    "DensityBand",
    "DensityMetrics",
    "EffectiveScheme",
    "FONT_FAMILIES",
    "FONT_SIZE_PT",
    "FakeStyleHints",
    "ICON_QSS_TOKEN_NAMES",
    "ICON_ROLES",
    "IconCacheKey",
    "IconRole",
    "LIGHT_COLOR_TOKENS",
    "LIGHT_CONTROL_SIZES",
    "LIGHT_QSS_TOKENS",
    "LIGHT_RADII",
    "LIGHT_ROLE_COLORS",
    "LIGHT_SPACING",
    "MAINWINDOW_QSS_RESOURCE",
    "MetricsBindingPort",
    "NullThemeIconProvider",
    "PlaceholderQssRenderer",
    "QSS_TOKEN_NAMES",
    "QssDocumentRenderer",
    "QssResourceBundle",
    "QssThemeBinding",
    "QssThemeBindingPort",
    "RecordingThemeBindingPort",
    "SIZE_PARTICIPANTS",
    "ThemeApplyError",
    "ThemeBindingPort",
    "ThemeBindingRegistry",
    "ThemeError",
    "ThemeFaultHooks",
    "ThemeHealth",
    "ThemeIconProvider",
    "ThemeMetricsApplier",
    "ThemeMode",
    "ThemeRollbackError",
    "ThemeService",
    "ThemeSettingsBinder",
    "ThemeSnapshot",
    "ThemeValidationError",
    "apply_committed_appearance",
    "apply_theme_chrome",
    "bind_qss",
    "bind_qss_text",
    "bind_widget_qss",
    "binding_count",
    "build_density_metrics",
    "compose_component_stylesheet",
    "compose_theme_runtime_applier",
    "compose_theme_service",
    "compose_theme_snapshot",
    "contrast_ratio",
    "current_density_metrics",
    "current_qss_tokens",
    "current_theme_binding",
    "current_theme_snapshot",
    "default_qss_binding",
    "default_theme_runtime",
    "install_theme_binding",
    "isolate_matplotlib_canvas",
    "preferences_from_appearance",
    "preferences_from_snapshot",
    "qss_bind_key",
    "qss_tokens_for_scheme",
    "rebind_qss_bindings",
    "render_application_stylesheet",
    "render_resource_stylesheet",
    "reset_qss_bindings_for_tests",
    "resolve_effective_scheme",
    "scheme_from_palette",
    "subscribe_theme_window",
    "theme_construction_batch",
    "watch_qss_tokens",
]
