"""Reusable Qt editors for Matplotlib component controllers.

The package depends on Controller objects only through their public interface.
Editors therefore remain reusable across concrete component roles.
"""

from .base import ComponentEditorBase
from .inline_spec_editors import (
    AxesAnchorEditor,
    InlineValueEditor,
    LegendAnchorEditor,
    LinePatternEditor,
    MarkerSpecEditor,
    NamedNumberEditor,
    NumberSequenceEditor,
    OptionalColorEditor,
    StringListEditor,
)
from .spec_editors import (
    AxisFormatterEditor,
    AxisLocatorEditor,
    AxisScaleEditor,
    FigureLayoutEditor,
    FontSpecEditor,
    MarkEveryEditor,
    NormSpecEditor,
    ScatterColorMapEditor,
    ScatterSizeMapEditor,
    StructuredValueEditor,
    TextBoxEditor,
    ZoomConnectorsEditor,
)
from .common import (
    DebouncedTextBinding,
    LineStyleEditor,
    NullableDoubleEditor,
    NumericTupleEditor,
    RangeEditor,
    ScatterStyleEditor,
    SpinePositionEditor,
    format_number_sequence,
    modification_succeeded,
    normalize_line_style,
    parse_number_sequence,
)
from .registry import EditorKey, EditorRegistry
from .inspector import (
    ComponentInspector,
    EditorProfile,
    EditorPlacement,
    EditorSection,
    SectionSpec,
    TreePresentationSpec,
)
from .inputs import (
    DataReferenceInput,
    InAxesInput,
    InterpolationOptionsInput,
    LineAppearanceInput,
    MultiSeriesDataReferenceInput,
    ScatterMappingInput,
)
from .profiles import register_production_profiles
from .sections import (
    AxesLayoutSection,
    DataReferenceSection,
    ImageInAxesSourceSection,
    LegendLocationSection,
    LineAppearanceSection,
    PaletteSection,
    PropertySection,
    ScatterAppearanceSection,
    TextContentSection,
    TextPositionSection,
    TextRenderSection,
    TextTransformSection,
    TextTypographySection,
)
from .context import (
    ComponentEditorManager,
    EditorContext,
    MessagePresenter,
)

__all__ = [
    "ComponentEditorBase",
    "AxesAnchorEditor",
    "AxisFormatterEditor",
    "AxisLocatorEditor",
    "AxisScaleEditor",
    "FigureLayoutEditor",
    "FontSpecEditor",
    "InlineValueEditor",
    "LegendAnchorEditor",
    "LinePatternEditor",
    "MarkEveryEditor",
    "MarkerSpecEditor",
    "NamedNumberEditor",
    "NormSpecEditor",
    "NumberSequenceEditor",
    "OptionalColorEditor",
    "ScatterColorMapEditor",
    "ScatterSizeMapEditor",
    "StringListEditor",
    "StructuredValueEditor",
    "TextBoxEditor",
    "ZoomConnectorsEditor",
    "DebouncedTextBinding",
    "EditorRegistry",
    "EditorKey",
    "ComponentInspector",
    "EditorProfile",
    "EditorPlacement",
    "EditorSection",
    "SectionSpec",
    "TreePresentationSpec",
    "DataReferenceInput",
    "InAxesInput",
    "InterpolationOptionsInput",
    "LineAppearanceInput",
    "MultiSeriesDataReferenceInput",
    "ScatterMappingInput",
    "register_production_profiles",
    "AxesLayoutSection",
    "DataReferenceSection",
    "ImageInAxesSourceSection",
    "PropertySection",
    "LineAppearanceSection",
    "ScatterAppearanceSection",
    "TextContentSection",
    "TextTypographySection",
    "TextTransformSection",
    "TextPositionSection",
    "TextRenderSection",
    "LegendLocationSection",
    "PaletteSection",
    "ComponentEditorManager",
    "EditorContext",
    "MessagePresenter",
    "LineStyleEditor",
    "NullableDoubleEditor",
    "NumericTupleEditor",
    "RangeEditor",
    "ScatterStyleEditor",
    "SpinePositionEditor",
    "format_number_sequence",
    "modification_succeeded",
    "normalize_line_style",
    "parse_number_sequence",
]
